### ISSUE TITLE
Cannot install v0.2.3.1.0 on macOS

### ISSUE THREAD

**Issue by changebo** [vinecopulib/rvinecopulib#70] opened 2017-12-25 23:05 UTC
Dear authors, 

I have problem installing the latest version of rvinecopulib (v0.2.3.1.0). Below are the installation messages.
```
> devtools::install_github("vinecopulib/rvinecopulib")
Downloading GitHub repo vinecopulib/rvinecopulib@master
from URL https://api.github.com/repos/vinecopulib/rvinecopulib/zipball/master
Installing rvinecopulib
'/usr/local/Cellar/r/3.4.3/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/ls/3nddvrtd1dl2m09ch7bn1rd80000gn/T/RtmpPpcAJa/devtools87383727f23a/vinecopulib-rvinecopulib-0a6617b'  \
  --library='/usr/local/lib/R/3.4/site-library' --install-tests 

* installing *source* package ‘rvinecopulib’ ...
** libs
clang++ -std=gnu++11 -I/usr/local/Cellar/r/3.4.3/lib/R/include -DNDEBUG -I../inst/include -pthread -I"/usr/local/lib/R/3.4/site-library/BH/include" -I"/usr/local/lib/R/3.4/site-library/Rcpp/include" -I"/usr/local/lib/R/3.4/site-library/RcppEigen/include" -I"/usr/local/lib/R/3.4/site-library/RcppThread/include" -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2 -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I/usr/local/Cellar/r/3.4.3/lib/R/include -DNDEBUG -I../inst/include -pthread -I"/usr/local/lib/R/3.4/site-library/BH/include" -I"/usr/local/lib/R/3.4/site-library/Rcpp/include" -I"/usr/local/lib/R/3.4/site-library/RcppEigen/include" -I"/usr/local/lib/R/3.4/site-library/RcppThread/include" -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2 -c bicop_wrappers.cpp -o bicop_wrappers.o
clang++ -std=gnu++11 -I/usr/local/Cellar/r/3.4.3/lib/R/include -DNDEBUG -I../inst/include -pthread -I"/usr/local/lib/R/3.4/site-library/BH/include" -I"/usr/local/lib/R/3.4/site-library/Rcpp/include" -I"/usr/local/lib/R/3.4/site-library/RcppEigen/include" -I"/usr/local/lib/R/3.4/site-library/RcppThread/include" -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include   -fPIC  -g -O2 -c vinecop_wrappers.cpp -o vinecop_wrappers.o
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/usr/local/Cellar/r/3.4.3/lib/R/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -o rvinecopulib.so RcppExports.o bicop_wrappers.o vinecop_wrappers.o -L/usr/local/Cellar/r/3.4.3/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
installing to /usr/local/lib/R/3.4/site-library/rvinecopulib/libs
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘rvinecopulib’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/3.4/site-library/rvinecopulib/libs/rvinecopulib.so':
  dlopen(/usr/local/lib/R/3.4/site-library/rvinecopulib/libs/rvinecopulib.so, 6): Symbol not found: __ZSt5Rcout
  Referenced from: /usr/local/lib/R/3.4/site-library/rvinecopulib/libs/rvinecopulib.so
  Expected in: flat namespace
 in /usr/local/lib/R/3.4/site-library/rvinecopulib/libs/rvinecopulib.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/3.4/site-library/rvinecopulib’
Installation failed: Command failed (1)
```

I can successfully install v0.2.0.1.0 using the following command, but not v0.2.2.1.0.
`devtools::install_github("vinecopulib/rvinecopulib@v0.2.0.1.0")`

Below is some information about my computer
- OS:
  System Version:	macOS 10.13.2 (17C88)
  Kernel Version:	Darwin 17.3.0
- R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
- Compiler: 
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Could you please help? Thanks in advance.

Bo

**Comment by tvatter** [comment] 2017-12-26 09:27
Hi,

I am also on OSX and I have no problem to install with gcc. However, I just tried clang and can't install either, so the issue is definitely with the compiler. I also just noticed that the same thing is happening in the CRAN build, so you're not alone ;)

I am trying to understand what happened in the new version of vinecopulib, but in the meantime, you can do for instance `brew install gcc` and then add 

```
CC=/usr/local/bin/gcc-7
CXX=/usr/local/bin/g++-7 
```

or something similar in .R/Makevars

**Comment by tvatter** [comment] 2017-12-26 09:44
Thomas, it appears that the problem comes from [those lines](https://github.com/vinecopulib/rvinecopulib/blob/master/inst/include/vinecopulib/misc/tools_interface.hpp#L17-L20)

**Comment by tvatter** [comment] 2017-12-26 09:47
Also, since most macOS users won't be able to install as long as this is not resolved, I'm upgrading to urgent. I should really test the package using clang or we should set-up travis for OSX, because this is really bad.

**Comment by tnagler** [comment] 2017-12-26 14:57
I guess this is a good opportunity to test #69. Bo, could you try installing with 
```r 
devtools::install_github("vinecopulib/rvinecopulib", ref = "cout-init")
``` 
?

**Comment by tvatter** [comment] 2017-12-26 15:02
It worked on my computer.

**Comment by changebo** [comment] 2017-12-26 22:50
Thanks @tnagler and @tvatter for your quick response! I can successfully install the dev branch now.

I got the following warning at the end of installation, not sure if it's critical.
```Warning in FUN(X[[i]], ...) : internal error -3 in R_decompress1```

**Comment by tnagler** [comment] 2017-12-27 17:32
Hm, I've never seen this message before and google doesn't seam to help either (found something like [this](https://stackoverflow.com/questions/10373098/error-in-fetchkey-internal-error-3-in-r-decompress1)). As long everything else works, I will assume it's not critical and close this issue ;)

**Closed by tnagler** 2017-12-27 17:32 UTC
Labels: bug, help wanted
